### ISSUE TITLE
Issue: If ASDF is already installed, the plugin fails

### ISSUE THREAD

**Issue by arevak** [osx-provisioner/role-asdf#1]
The git clone fails in `tasks/nstall.yml` if asdf is already installed for the user.  Fix this with a simple check, submitting a PR soon.

**Comment by arevak** [comment]
https://github.com/osx-provisioner/role-asdf/pull/2 Should fix it

**Comment by niall-byrne** [comment]
First of all thanks for taking time to report the issue and the PR.

Do you mind if I ask how you discovered this?

I just realized the molecule tests I'm running have an idempotentcy check:  ie.  they run the test and install it, and then run again to ensure they don't error or change anything.

You can view the tests here:  https://github.com/osx-provisioner/role-asdf/tree/master/molecule
(They run in the github workflow for this repository.)

Could you give more details on how to reproduce the problem?  Ideally we'd want to write a test for this scenario.
Maybe you specifically mean it's when a user has installed asdf manually that this problem comes up?
Perhaps some non-standard install of asdf causes the issue?

**Comment by arevaklg** [comment]
Yeah, you have it exactly.  Ill admit this is my first time trying this sort of thing.  The way I see it is there is a small chicken and the egg problem that I haven't figured out the right way to resolve yet.  I want to use ASDF to keep my language installs clean from my system installs yet ansible is python based.  So I was using a shell script to install ASDF and then python and ansible.  Then using this role to enforce the configuration for asdf and install other languages I needed (elixir and erlang).

**Comment by arevak** [comment]
Yeah, you have it exactly.  Ill admit this is my first time trying this sort of thing.  The way I see it is there is a small chicken and the egg problem that I haven't figured out the right way to resolve yet.  I want to use ASDF to keep my language installs clean from my system installs yet ansible is python based.  So I was using a shell script to install ASDF and then python and ansible.  Then using this role to enforce the configuration for asdf and install other languages I needed (elixir and erlang).

**Comment by niall-byrne** [comment]
Ok I see.  You might be interested in [this](https://github.com/osx-provisioner/mac_maker) project, it's a self contained Ansible executable (a binary that comes with it's own interpreter).  It's another possible solution to the "how to bootstrap Ansible" problem.  (I use it to provision ASDF on new macs.)

Would you be able to share (all or part of) the script that does your install?  We could probably use that to recreate the scenario and then add a test to this role so we know it's fixed.

**Comment by arevak** [comment]
That is interesting.  Sure I can share a reproduction case.  It will be a little bit Tom I can get to it though, probably tomorrow. It's a pretty simple script.  Essentially just what ASDF has on their website but automating the plugin add for python and installing latest then pip install ansible

**Comment by arevak** [comment]
Essentially this.  Sorry it took so long.

```
#!/bin/zsh

# Install HomeBrew
brew >>& /dev/null
if [ $? -ne 0 ]; then
        printf "Installing Homebrew ... "
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        printf "Done\n"
else
        echo "Homebrew is already installed"
fi

# Install ASDF
which asdf >>& /dev/null
if [ $? -ne 0 ]; then
        printf "Installing ASDF-VM (https://github.com/asdf-vm/asdf)"
        brew install asdf
        echo -e "\n. $(brew --prefix asdf)/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc
        printf "Done\n"
else
        echo "ASDF is already installed"
fi

# Install ASDF-Python, to keep system python clean
printf "Installing ASDF-VM [Python]"
asdf plugin-add python
asdf install python latest
asdf global python latest
pip3 install --upgrade pip
asdf reshim python
pip3 install ansible
```

**Comment by niall-byrne** [comment]
Ok, so it's a homebrew install that's conflicting with the ansible install.

We can do a couple of things off the top of my head:

- I really would like to encourage you to try [mac_maker](https://github.com/osx-provisioner/mac_maker) as this is the exact scenario it was written to help with.  You could for example, extend [this](https://github.com/osx-provisioner/profile-example/blob/master/profile/vars/main.yml) very simply profile repo to achieve what you want.  
  - `mac_maker apply github https://github.com/myuser/myrepo` and go get a coffee
  - This would install homebrew (if needed), asdf, python, and any other brew dependencies you might have
  - Does not modify the existing system Python
  - Would require you uninstall the homebrew installed ASDF head of time.

- Or we could split up the `installation` of ASDF from the `management` of ASDF inside this role.  Maybe allow an option to ignore existing installs, but still try and manage them... perhaps trying to execute "asdf" is a better check then seeing if the folder exists?

- I believe you could also just select what you want to install in this case using Ansible tags.  If you take a look [here](https://github.com/arevak/role-asdf/blob/master/tasks/main.yml) you'll see each step is tagged separately, this should allow you to extract only the behaviour you want from the role. (ie. you select the tags you want ansible to run with CLI options at run time... I think the imported task file should pickup the tags correctly, I haven't tested that behaviour yet though.)

**Comment by arevak** [comment]
I'll take a look at mac_maker happily when I have the time.  I think you will run into the same issue.  All my PR is doing here is saying, if the folder exists, then don't clone.  That might point at a bug with the git clone task since `clone: yes` which is the default, should probably do a more robust check.

**Comment by niall-byrne** [comment]
I think as a short term work around, maybe try the tag solution first.  In the meantime, I'll take another look at the clone step.
